// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6z5tZ9Vzh_8pFJbFtGLDDDwJWX6s5QB4',
    appId: '1:207067463949:web:63f4b5d0dc9a68062d3044',
    messagingSenderId: '207067463949',
    projectId: 'chaos-8bd2d',
    authDomain: 'chaos-8bd2d.firebaseapp.com',
    databaseURL: 'https://chaos-8bd2d.firebaseio.com',
    storageBucket: 'chaos-8bd2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7CGyjCSDJqK4eYDqckHkjTVhRiJecAaI',
    appId: '1:207067463949:android:eaa26b855da85f682d3044',
    messagingSenderId: '207067463949',
    projectId: 'chaos-8bd2d',
    databaseURL: 'https://chaos-8bd2d.firebaseio.com',
    storageBucket: 'chaos-8bd2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcH21qNMzBoXE9OktqmVpqTXQKwsjvD4A',
    appId: '1:207067463949:ios:b08807f18982e1832d3044',
    messagingSenderId: '207067463949',
    projectId: 'chaos-8bd2d',
    databaseURL: 'https://chaos-8bd2d.firebaseio.com',
    storageBucket: 'chaos-8bd2d.firebasestorage.app',
    iosBundleId: 'com.example.gittest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcH21qNMzBoXE9OktqmVpqTXQKwsjvD4A',
    appId: '1:207067463949:ios:b08807f18982e1832d3044',
    messagingSenderId: '207067463949',
    projectId: 'chaos-8bd2d',
    databaseURL: 'https://chaos-8bd2d.firebaseio.com',
    storageBucket: 'chaos-8bd2d.firebasestorage.app',
    iosBundleId: 'com.example.gittest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6z5tZ9Vzh_8pFJbFtGLDDDwJWX6s5QB4',
    appId: '1:207067463949:web:8008522cf2561a112d3044',
    messagingSenderId: '207067463949',
    projectId: 'chaos-8bd2d',
    authDomain: 'chaos-8bd2d.firebaseapp.com',
    databaseURL: 'https://chaos-8bd2d.firebaseio.com',
    storageBucket: 'chaos-8bd2d.firebasestorage.app',
  );
}
